### ISSUE TITLE
run.Reader can't handle mzML's with UV data

### ISSUE THREAD

**Issue by pyeguy** [pymzml/pymzML#119]
I frequently have mzML chromatograms w/ UV data associated with them. This registers as a spec w/ `ms_level` as 0 which throws a `KeyError` when doing the `ms_precisions` look up. 

I'm going to submit a pull request that adds a 0 key w/ an arbitrary precision of 0.001 which i use to fix this issue locally. Let me know if that default value should be higher or lower in your opinion.

**Comment by pyeguy** [comment]
added #120 to address this

**Comment by MKoesters** [comment]
Hi and thanks for reporting this,
I personally have never worked with UV data, so I cant say what a reasonable default would look like.
Since this is just a minor change without to much implications (I hope) I'll just accept your pull request.
But I'll have a look at this kind of data more closely in the next week, since I'm traveling a lot currently and I'm a bit short on time for open source projects.

Best,
Manuel

**Comment by pyeguy** [comment]
Sounds good, I'm not sure what the precision is for most diode array UV abs detectors. I can do some poking around and see if there are some common manufacturer stats that could be averaged for a reasonable default.
