### ISSUE TITLE
I need to extract 

### ISSUE THREAD

**Issue by amnahsiddiqa** [pymzml/pymzML#276]
I need toe extract a cvparam ; MS:1000130 for polarity  of scans ; 
looking at #219 ; I wanted to know can we not access any information using  accession like "MS:1000130" directly; it might be a naive question but I am just getting started; 
'
<spectrumList count="780" defaultDataProcessingRef="ThermoRawFileParserProcessing">
        <spectrum id="controllerType=0 controllerNumber=1 scan=1" index="0" defaultArrayLength="1072">
          <cvParam cvRef="MS" accession="MS:1000130" value="" name="positive scan" />
     
Many Thanks,
Amnah

**Comment by MKoesters** [comment]
Hi Amnah,

Accessing the polarity can be done using the tag you posted.

```
In [1]: import pymzml                                                                         

In [2]: with pymzml.run.Reader('/home/manuel/Data/Proteomics/mzML_examples/200414_HILIC_pos_Ph
   ...: ospholipid_Soy-Soybean Phospholipid.mzML') as run: 
   ...:     for spec in run: 
   ...:         print(spec["MS:1000130"]) # positive scan 
   ...:         print(spec["MS:1000129"]) # negative scan 
   ...:         break 
   ...:                                                                                       
True
None

In [3]:  

```

Currently, its a bit awkward, as you see the return value of `spec["MS:1000130"]` is True, since its actually a positive scan.
A return value of `None` would mean, that the tag (in this case MS:1000129) was not found.

Loading a run measured in negative mode would result in `spec["MS:1000130"]` returning `None` and `spec["MS:1000130"]` returning True

Hope this help and feel free to ask if you need more information :)

Best,
Manuel

**Comment by amnahsiddiqa** [comment]
hey Manuel, Thanks much. Closing the issue now.
