### ISSUE TITLE
How to export or extract PDA spectra

### ISSUE THREAD

**Issue by ZewSam** [pymzml/pymzML#289]
Hello, I am not sure how to extract PDA spectra from mzML file with pymzml.  I set spec.ms.level = 0 or None, but neither of them worked.  Can anyone provide an example script? Thank you.

**Comment by MKoesters** [comment]
Hey @ZewSam,

Since I never worked with PDA spectra, would you be able to supply a example mzML?

Best,
Manuel

**Comment by ZewSam** [comment]
Thanks @MKoesters, I am just wondering how I should share the example mzML file with you?

**Comment by MKoesters** [comment]
You could either upload it at a sharing service of your choice (if you need with a password which you can share with me via mail).
Or you could copy and paste one of the PDA spectra elements (the ones starting with <spectrum ..>) from your mzML directly into this issue.
I'll have a quick look online and in case I find one, I can also try to fix your issue with that, however if the issue is the way your mzML is written, this maybe not that useful

**Comment by ZewSam** [comment]
Thanks @MKoesters.  Would you please provide your email address so I can send the example file? Thanks again.

**Comment by MKoesters** [comment]
Hi @ZewSam,

My email is: manuel.koesters@unibe.ch
