### ISSUE TITLE
Define __deepcopy__ to lessen the pain of deRef

### ISSUE THREAD

**Issue by Chris7** [pymzml/pymzML#45]
I've noticed while profiling that creating a deepcopy is quite expensive. This could be greatly accelerated by defining a **deepcopy** method on Spectrum to copy over the parts of interest.

**Comment by fu** [comment]
Hi Chris,

thanks for the feedback. We are currently working on  a new release where we removed the need for deepcopy all together without losing speed. Since we have included some cool new features, we would like to keep it private to improve our chance to publish the module again, so sorry about that.

Cheers

.c
  
Nice work on pyQuant, btw :) ... We are trying to publish our module pyQms since 0.5y now without success ... maybe we should have tried MCP as well 👍

**Comment by Chris7** [comment]
Thanks for the update @fu! I'm looking forward to those changes.

Thanks for your comments on PyQuant and good luck with pyQms ( I actually have been waiting for the deepcopy changes so I can switch over PyQuant's mzml parser to use this). There is a definite need for more open source/cross platform solutions for quantification of ms data. It seems everyone jumped on the multiple search engine band wagon and never applied the same logic to quantification :). Wrt pyQms -- there is a tool I co-wrote, Wooey, that might be useful for bootstrapping a GUI (I saw you have a flask GUI landing page for it). The Pandey lab uses it to run PyQuant and other analyses. Feel free to close this --- or to keep it open as a reminder of things to talk about with the next release.

**Comment by JB-MS** [comment]
@Chris7  Have you tried out the new version of pymzML (2.0.2, also on pypi).

Is the performance better for your requirements now? If not, maybe we can work on a solution together?

**Comment by fu** [comment]
Hi Chris,

yes indeed, nobody applied the logic to multiple quant engines but people are thinking about it. maybe jsut a matter of time until there will be a solution ;) We are currently putting a "unified_quant.csv" into ursgal in order to address that. :)

So for you issue, I hope you switched to pymzML v2.0 and enjoy the fast random access in gziped files :)

Cheers

.c

PS can we close this issue then ?
